#!/usr/bin/env python3
"""Write the generated indexes: one way in for every tracked area of the repo.

    <python> bench/build_index.py            # rewrite them all
    <python> bench/build_index.py --check    # exit 1 when any is stale

**The one source is `git ls-files`** (owner, 2026-10-05: "do not index
anything that isnt git tracked"). Nothing here walks a directory, so an
untracked tree (`internal/`, `coderef/`, a session's scratch) cannot appear
in an index and there is no exclusion list to go stale. A new file enters its
index when it is added to git: `git add -- <file>`, run this, commit both.
`--check` also reads every link back out of the written indexes and fails on
one whose target is not tracked.

What is written, and from what:

`INDEX.md` (the repo root)
    The pack's own modules: name, the node ids each defines (read with `ast`
    from its `node_id=` arguments) and the first sentence of its docstring,
    grouped by filename prefix. Then the root's other files, the top-level
    directories with where each one's index is, and a short listing for each
    directory small enough not to need a file of its own.

`bench/INDEX.md`
    Every script directly under `bench/` by the first sentence of its
    docstring, grouped by filename prefix; then the other files there (arm
    manifests by their own `what` line) and the subfolders.

`bench/results/INDEX.md`
    Every `.md` record by month, newest first: date and lane from the
    filename, the record's first heading, and its verdict when it states one.
    A record may carry `lane:` or `verdict:` near its top (plain or bold),
    which overrides the one and fills the other; no old record was edited.
    Data files are counted per month, not listed.

`workflows/INDEX.md`
    Every graph by directory: the generator's own one-line note for it, when
    `workflows/build_workflows.py --dump-graphs` exists to say it, and the
    chain read off the graph itself (checkpoint, LoRAs, and which of this
    pack's nodes it wires).

Already indexed elsewhere and only pointed at: `docs/` by the hand-written
router `docs/wiki/index.md`, and `prompt_bank/` by `docs/prompt_bank.md`.

Every description is the file's own words (a docstring, a heading, a `what`
key); nothing is written here about a file. All of it is generated: edit the
source and run this again, never an index. Nothing is moved, because a path
is an identifier in this repo. The output carries no date and no commit, so
`--check` is a plain comparison.

Reads source with `ast` and imports no script. The one thing it runs is
`workflows/build_workflows.py --dump-graphs`, which returns before that
script reaches ComfyUI. No torch, no card, no server.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
import sys
from collections import Counter
from functools import lru_cache
from pathlib import Path

BENCH = Path(__file__).resolve().parent
REPO = BENCH.parent
RESULTS = BENCH / "results"

MARKER = "Generated by `bench/build_index.py`"

# reasoned: the script families mryellow's brief of 2026-10-05 named, largest
# first; everything else is one alphabetical list, because a group of two or
# three scripts is easier to find by name than by a heading.
BENCH_PREFIXES = ("check", "measure", "analyze", "grade", "compare", "build", "probe")

# reasoned: a root-module family is a filename prefix at least this many
# modules share; a smaller one is not a group, it is a name.
MODULE_FAMILY_MIN = 2

# reasoned: long enough for a first sentence to fit whole on the day this was
# written; a docstring that opens with a paragraph gets cut.
SUMMARY_LIMIT = 240

# reasoned: `lane:` and `verdict:` are read only near the top, so a record
# that quotes the words further down in prose is not misread.
HEADER_LINES = 15

# reasoned: a top-level directory with at most this many tracked files is
# listed inside the root index; a larger one gets, or already has, its own.
SMALL_DIRECTORY = 30

#: Top-level directories that gain a file with every commit. Neither their
#: files nor their count go in the index: an index that every commit by every
#: session has to regenerate is the shared file the fragments were made to
#: get rid of. Value: (the file that explains the directory, what to say).
GROWS_WITH_EVERY_COMMIT = {
    "changelog.d": ("changelog.d/README.md", "one file per changelog entry; not listed and not counted"),
}

#: Top-level directories whose index already exists and is not written here.
INDEXED_ELSEWHERE = {
    "docs": ("docs/wiki/index.md", "the hand-written router"),
    "prompt_bank": ("docs/prompt_bank.md", "the prompt catalogue"),
}

DATED = re.compile(r"^(\d{4})-(\d{2})-(\d{2})_(.+)$")
FIELD = re.compile(r"^\**(lane|verdict)\**:\**\s*(.+?)\s*$", re.I)
LINK = re.compile(r"\]\(([^)#\s]+)(?:#[^)]*)?\)")
JSON_SAYS = ("what", "description", "_comment", "comment", "note", "purpose")
#: Files whose first line says nothing about them; named by kind instead.
KIND = {".jpg": "image", ".jpeg": "image", ".png": "image", ".webp": "image",
        ".lock": "lock file", ".safetensors": "weights", ".toml": "TOML",
        ".gitignore": "git ignore rules"}


# -------------------------------------------------------------- tracked files

@lru_cache(maxsize=1)
def tracked() -> tuple[str, ...]:
    """Every tracked path that is on disk, repo-relative, sorted. The one source."""
    done = subprocess.run(["git", "-C", str(REPO), "ls-files", "-z"], capture_output=True)
    if done.returncode != 0:
        raise SystemExit("bench/build_index.py reads `git ls-files` and nothing else; "
                         f"git said: {done.stderr.decode(errors='replace').strip()}")
    names = (n.decode("utf-8", "surrogateescape") for n in done.stdout.split(b"\0") if n)
    return tuple(sorted(n for n in names if (REPO / n).is_file()))


def under(directory: str, *, direct: bool = False) -> list[str]:
    """Tracked paths under `directory` ('' is the root); `direct` drops subfolders."""
    prefix = f"{directory}/" if directory else ""
    out = [n for n in tracked() if n.startswith(prefix)]
    if direct:
        out = [n for n in out if "/" not in n[len(prefix):]]
    return out


# ------------------------------------------------------------ what a file says

def cell(text: str) -> str:
    """Text made safe for one markdown table cell."""
    return " ".join(str(text).split()).replace("|", "\\|")


def clip(text: str) -> str:
    text = " ".join(text.split())
    if len(text) > SUMMARY_LIMIT:
        text = text[:SUMMARY_LIMIT].rsplit(" ", 1)[0] + " ..."
    return text


def first_sentence(doc: str) -> str:
    """The opening sentence of a docstring, joined across wrapped lines."""
    taken: list[str] = []
    for line in doc.strip().split("\n\n", 1)[0].splitlines():
        taken.append(line.strip())
        if line.rstrip().endswith((".", "?", "!", ":", ".**", "?**")):
            break
    return clip(" ".join(t for t in taken if t))


def _read(rel: str) -> str:
    return (REPO / rel).read_text(encoding="utf-8", errors="replace")


def _tree(rel: str):
    try:
        return ast.parse(_read(rel))
    except SyntaxError:
        return None


def python_says(rel: str) -> str:
    tree = _tree(rel)
    if tree is None:
        return "(does not parse)"
    doc = ast.get_docstring(tree)
    return first_sentence(doc) if doc else "(no docstring)"


def node_ids(rel: str) -> list[str]:
    """The `node_id="..."` values a module passes, in source order."""
    tree = _tree(rel)
    if tree is None:
        return []
    found = []
    for node in ast.walk(tree):
        if isinstance(node, ast.keyword) and node.arg == "node_id" \
                and isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
            found.append((node.value.lineno, node.value.value))
    return [name for _line, name in sorted(found)]


def markdown_heading(rel: str) -> str:
    text = _read(rel)
    if text.startswith("---"):
        # a skill or a record with frontmatter: its own description line
        for line in text.split("\n---", 1)[0].splitlines():
            if line.startswith("description:"):
                return clip(line.split(":", 1)[1].strip().strip('"'))
    for line in text.splitlines():
        if line.startswith("#"):
            return clip(line.lstrip("#").strip())
    return text_says(rel)


def graph_chain(data) -> str | None:
    """What a ComfyUI graph wires, in a line, or None when `data` is not a graph."""
    if isinstance(data, dict) and isinstance(data.get("nodes"), list):
        return f"ComfyUI editor graph, {len(data['nodes'])} nodes"
    if not (isinstance(data, dict) and data
            and all(isinstance(v, dict) and "class_type" in v for v in data.values())):
        return None
    models, loras, ours = [], [], []
    for node in data.values():
        for key, value in (node.get("inputs") or {}).items():
            if not isinstance(value, str) or not value.endswith((".safetensors", ".gguf")):
                continue
            if key == "unet_name" and value not in models:
                models.append(value)
            elif "lora" in key.lower() and value not in loras:
                loras.append(value)
        kind = node["class_type"]
        if kind.startswith("MiniMaxH3") and kind[len("MiniMaxH3"):] not in ours:
            ours.append(kind[len("MiniMaxH3"):])
    parts = [f"{len(data)} nodes"]
    if models:
        parts.append("checkpoint " + ", ".join(f"`{m}`" for m in models))
    if loras:
        parts.append("LoRA " + ", ".join(f"`{name}`" for name in loras))
    if ours:
        parts.append("pack nodes " + ", ".join(sorted(ours)))
    return "; ".join(parts)


def json_says(rel: str) -> str:
    try:
        data = json.loads(_read(rel))
    except ValueError:
        return "(JSON that does not parse)"
    if isinstance(data, dict):
        for key in JSON_SAYS:
            if isinstance(data.get(key), str) and data[key].strip():
                return clip(data[key])
    chain = graph_chain(data)
    if chain:
        return chain
    # No count of keys or items: an index line that moves whenever a baseline
    # gains an entry makes the index stale for a reason nobody can read (the
    # node manifest did exactly that on 2026-10-05).
    kind = "an object" if isinstance(data, dict) else "a list" if isinstance(data, list) else type(data).__name__
    return f"(JSON, {kind}; it carries no description)"


def text_says(rel: str) -> str:
    """The first line that says something, for a file with no better structure."""
    try:
        lines = _read(rel).splitlines()
    except OSError:
        return "(unreadable)"
    for line in lines:
        if line.startswith("#!"):
            continue
        stripped = line.strip().lstrip("#/*-; ").strip()
        if stripped:
            return clip(stripped)
    return "(empty)"


def says(rel: str) -> str:
    suffix = Path(rel).suffix.lower() or Path(rel).name
    if suffix in KIND:
        return f"({KIND[suffix]})"
    if suffix == ".py":
        return python_says(rel)
    if suffix == ".md":
        return markdown_heading(rel)
    if suffix == ".json":
        return json_says(rel)
    return text_says(rel)


def link(rel: str, base: str, label: str | None = None) -> str:
    """A markdown link to tracked path `rel` from an index in directory `base`."""
    target = rel[len(base) + 1:] if base and rel.startswith(base + "/") else \
        ("../" * (base.count("/") + 1) + rel if base else rel)
    return f"[`{label or Path(rel).name}`]({target})"


def listing(paths: list[str], base: str, *, name=None) -> list[str]:
    """A table of tracked paths, each named relative to the index's directory."""
    if name is None:
        def name(rel):
            return rel[len(base) + 1:] if base and rel.startswith(base + "/") else rel
    out = ["| file | what it says |", "|---|---|"]
    out += [f"| {link(rel, base, name(rel))} | {cell(says(rel))} |" for rel in paths]
    return out + [""]


def header(title: str, lines: list[str]) -> list[str]:
    return [f"# {title}", "", f"{MARKER} from `git ls-files`. Do not edit:",
            "change the file an entry describes and run the generator.",
            "`bench/build_index.py --check` says whether this file is current.",
            *lines, ""]


# ------------------------------------------------------------------- INDEX.md

def family(name: str, counts: Counter) -> str:
    head = name.split("_", 1)[0]
    return head if "_" in name and counts[head] >= MODULE_FAMILY_MIN else "rest"


def build_root() -> str:
    direct = under("", direct=True)
    modules = [n for n in direct if n.endswith(".py")]
    counts = Counter(m.split("_", 1)[0] for m in modules if "_" in m)
    groups: dict[str, list[str]] = {}
    for m in modules:
        groups.setdefault(family(m[:-3], counts), []).append(m)
    order = sorted(g for g in groups if g != "rest") + (["rest"] if "rest" in groups else [])

    out = header("The repo, by tracked file", [
        "An entry's text is the file's own: a docstring's first sentence, a",
        "heading, a `what` line. `README.md` says what ships and why, and",
        "`docs/wiki/index.md` routes a question to the document that answers it;",
        "this file only says what is here.",
    ])
    out += ["## The pack's modules", "",
            "The node ids are the ones each module passes as `node_id=`; a module",
            "with none is a helper the others import.", ""]
    for g in order:
        out += [f"### {g + '_*' if g != 'rest' else 'the rest'}", "",
                "| module | nodes it defines | what it says it does |", "|---|---|---|"]
        for m in groups[g]:
            ids = ", ".join(f"`{i}`" for i in node_ids(m)) or ""
            out.append(f"| {link(m, '')} | {ids} | {cell(python_says(m))} |")
        out.append("")

    others = [n for n in direct if not n.endswith(".py") and n != "INDEX.md"]
    out += ["## Other files at the root", ""] + listing(others, "")

    tops = Counter(n.split("/", 1)[0] for n in tracked() if "/" in n)
    out += ["## Directories", "", "| directory | tracked files | where its index is |", "|---|---|---|"]
    small = []
    for d in sorted(tops):
        if d in GROWS_WITH_EVERY_COMMIT:
            target, what = GROWS_WITH_EVERY_COMMIT[d]
            out.append(f"| `{d}/` | | [`{target}`]({target}), {what} |")
            continue
        if d in INDEXED_ELSEWHERE:
            target, what = INDEXED_ELSEWHERE[d]
            where = f"[`{target}`]({target}), {what}"
        elif f"{d}/INDEX.md" in WRITERS:
            where = f"[`{d}/INDEX.md`]({d}/INDEX.md)"
            if d == "bench":
                where += " and [`bench/results/INDEX.md`](bench/results/INDEX.md) for the records"
        elif tops[d] <= SMALL_DIRECTORY:
            where = f"[below](#{d.strip('.')})"
            small.append(d)
        else:
            where = "(none)"
        out.append(f"| `{d}/` | {tops[d]} | {where} |")
    out.append("")
    for d in small:
        out += [f"## {d}/", ""] + listing(under(d), "", name=lambda rel, d=d: rel[len(d) + 1:])
    return "\n".join(out).rstrip() + "\n"


# ------------------------------------------------------------- bench/INDEX.md

def bench_group(name: str) -> str:
    head = name.split("_", 1)[0]
    return head if head in BENCH_PREFIXES and "_" in name else "rest"


def build_bench() -> str:
    direct = under("bench", direct=True)
    scripts = [n for n in direct if n.endswith((".py", ".sh"))]
    groups: dict[str, list[str]] = {g: [] for g in (*BENCH_PREFIXES, "rest")}
    for rel in scripts:
        groups[bench_group(Path(rel).name)].append(rel)

    out = header("bench/, by script", [
        "`docs/checks.md` is the index of the checks with what each defends;",
        "this file is only a way to find a script by what it says it does.",
    ])
    out += ["| group | scripts |", "|---|---|"]
    titles = {g: f"`{g}_*`" for g in BENCH_PREFIXES} | {"rest": "the rest"}
    anchors = {g: g for g in BENCH_PREFIXES} | {"rest": "the-rest"}
    out += [f"| [{titles[g]}](#{anchors[g]}) | {len(paths)} |" for g, paths in groups.items()]
    out.append("")
    for g, paths in groups.items():
        out += [f"## {g if g != 'rest' else 'the rest'}", "",
                "| script | what it says it does |", "|---|---|"]
        out += [f"| {link(rel, 'bench')} | {cell(says(rel))} |" for rel in paths]
        out.append("")

    other = [n for n in direct if n not in scripts and n != "bench/INDEX.md"]
    out += ["## Other files", "",
            "Arm manifests and the like; a manifest's line is its own `what`.", ""]
    out += listing(other, "bench")

    folders = Counter(n.split("/")[1] for n in under("bench") if n.count("/") >= 2)
    out += ["## Subfolders", ""]
    for folder in sorted(folders):
        if folder == "results":
            out += ["### results", "",
                    f"{folders[folder]} tracked files: [`results/INDEX.md`](results/INDEX.md).", ""]
            continue
        out += [f"### {folder}", ""]
        out += listing(under(f"bench/{folder}"), "bench",
                       name=lambda rel, f=folder: rel[len(f"bench/{f}/"):])
    return "\n".join(out).rstrip() + "\n"


# ----------------------------------------------------- bench/results/INDEX.md

def record_fields(rel: str) -> tuple[str, dict[str, str]]:
    """(first heading, {'lane': ..., 'verdict': ...} when the record states them)."""
    heading, fields = "", {}
    for number, line in enumerate(_read(rel).splitlines()):
        if not heading and line.startswith("#"):
            heading = line.lstrip("#").strip()
        if number < HEADER_LINES and (m := FIELD.match(line.strip())):
            # `**Verdict: not a fix.** The softened ...` states the verdict in
            # the bold run; what follows it is the argument.
            fields.setdefault(m.group(1).lower(), m.group(2).split("**", 1)[0].strip("* "))
        if heading and number >= HEADER_LINES:
            break
    return heading or "(no heading)", fields


def build_results() -> str:
    months: dict[str, list[tuple[str, str, str, str, str]]] = {}
    data: Counter = Counter()
    undated: list[str] = []
    for rel in under("bench/results", direct=True):
        name = Path(rel).name
        if name == "INDEX.md":
            continue
        m = DATED.match(name)
        if not m:
            undated.append(rel)
            continue
        month = f"{m.group(1)}-{m.group(2)}"
        if not name.endswith(".md"):
            data[month] += 1
            continue
        heading, fields = record_fields(rel)
        lane = fields.get("lane") or m.group(4).split("_", 1)[0].removesuffix(".md")
        months.setdefault(month, []).append(
            (f"{m.group(1)}-{m.group(2)}-{m.group(3)}", lane, name, heading, fields.get("verdict", "")))

    out = header("bench/results/, by record", [
        "",
        "One row per tracked `.md` record in this directory, newest month",
        "first. The date and the lane are the filename's; a record that carries",
        "a `lane:` or `verdict:` line near its top overrides the one and fills",
        "the other, and an empty verdict cell means the record has no such",
        "line, not that it reached none. The `.json` and `.jsonl` files beside",
        "the records are their data and are counted, not listed. Nothing here",
        "replaces `docs/evidence.md`, which says what the records established.",
    ])
    for month in sorted(set(months) | set(data), reverse=True):
        rows = sorted(months.get(month, []), key=lambda r: (r[0], r[2]), reverse=True)
        out += [f"## {month}", ""]
        if rows:
            out += ["| date | lane | record | verdict |", "|---|---|---|---|"]
            out += [f"| {date} | {cell(lane)} | [{cell(heading)}]({name}) | {cell(verdict)} |"
                    for date, lane, name, heading, verdict in rows]
            out.append("")
        if data[month]:
            out += [f"Data files dated this month and not listed: {data[month]}.", ""]

    folders = Counter(n.split("/")[2] for n in under("bench/results") if n.count("/") >= 3)
    if folders:
        out += ["## Directories", "", "| directory | tracked files | what its README says |", "|---|---|---|"]
        for folder in sorted(folders):
            readme = f"bench/results/{folder}/README.md"
            if readme in tracked():
                out.append(f"| [`{folder}/`]({folder}/README.md) | {folders[folder]} | "
                           f"{cell(markdown_heading(readme))} |")
            else:
                out.append(f"| `{folder}/` | {folders[folder]} | (no README) |")
        out.append("")
    if undated:
        out += ["## Not dated", ""] + listing(undated, "bench/results")
    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------- workflows/INDEX.md

def generator_notes() -> dict[str, dict]:
    """`build_workflows.py --dump-graphs`: relative graph path -> label, task, note.

    Empty when the generator has no such flag or cannot run here; the index
    then says so and carries the chain column alone.
    """
    script = REPO / "workflows" / "build_workflows.py"
    if "--dump-graphs" not in script.read_text(encoding="utf-8"):
        return {}
    import os
    env = dict(os.environ, CUDA_VISIBLE_DEVICES="")
    done = subprocess.run([sys.executable, str(script), "--dump-graphs"],
                          capture_output=True, text=True, env=env, cwd=str(REPO))
    # Loud, never an empty map: an index rebuilt without the notes would
    # differ from the committed one, and `--check` would call a correct
    # index stale.
    if done.returncode != 0:
        raise SystemExit("workflows/build_workflows.py --dump-graphs failed, so the workflows "
                         f"index cannot be built: {done.stderr.strip()[-400:]}")
    try:
        return json.loads(done.stdout)
    except ValueError as exc:
        raise SystemExit(f"workflows/build_workflows.py --dump-graphs did not print JSON: {exc}")


def build_workflows() -> str:
    notes = generator_notes()
    graphs = [n for n in under("workflows") if n.endswith(".json")]
    by_dir: dict[str, list[str]] = {}
    for rel in graphs:
        by_dir.setdefault(str(Path(rel).parent), []).append(rel)

    out = header("workflows/, by graph", [
        "Never edit a graph either: `workflows/build_workflows.py` writes them.",
        "",
        "The chain column is read off each graph: how many nodes, its",
        "checkpoint and LoRAs, and which of this pack's nodes it wires (the",
        "`MiniMaxH3` prefix dropped). " + (
            "The note is the generator's own line for the graph."
            if notes else
            "The generator's one-line note for each graph is not shown: it lives "
            "inside `build_workflows.py::main` and no flag prints it yet."),
        "`docs/prompt_bank.md` catalogues the prompts; this lists the graphs.",
    ])
    rest = [n for n in under("workflows") if not n.endswith(".json") and n != "workflows/INDEX.md"]
    out += ["## The generator and its files", ""] + listing(
        rest, "workflows", name=lambda rel: rel[len("workflows/"):])
    for d in sorted(by_dir, key=lambda p: (p.count("/"), p)):
        title = "workflows/ (the shipped graphs)" if d == "workflows" else d + "/"
        out += [f"## {title}", ""]
        if notes:
            out += ["| graph | the generator's note | chain |", "|---|---|---|"]
        else:
            out += ["| graph | chain |", "|---|---|"]
        for rel in by_dir[d]:
            try:
                chain = graph_chain(json.loads(_read(rel))) or "(not a graph)"
            except ValueError:
                chain = "(JSON that does not parse)"
            entry = notes.get(rel[len("workflows/"):]) or notes.get(Path(rel).name) or {}
            row = f"| {link(rel, 'workflows', Path(rel).name)} | "
            if notes:
                row += f"{cell(entry.get('note', ''))} | "
            out.append(row + f"{cell(chain)} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------------- main

WRITERS = {
    "INDEX.md": build_root,
    "bench/INDEX.md": build_bench,
    "bench/results/INDEX.md": build_results,
    "workflows/INDEX.md": build_workflows,
}


def untracked_links(index_rel: str, text: str) -> list[str]:
    """Link targets in a generated index that are not tracked files."""
    base = Path(index_rel).parent
    known = set(tracked())
    bad = []
    for target in LINK.findall(text):
        if "://" in target:
            continue
        resolved = Path(*[p for p in (base / target).parts])
        parts: list[str] = []
        for part in resolved.parts:
            if part == "..":
                parts.pop()
            elif part != ".":
                parts.append(part)
        rel = "/".join(parts)
        if rel not in known and rel not in WRITERS:
            bad.append(target)
    return bad


def main() -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="write nothing; exit 1 when an index is stale or links an untracked file")
    args = parser.parse_args()

    problems = []
    for rel, build in WRITERS.items():
        path = REPO / rel
        text = build()
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        bad = untracked_links(rel, text if not args.check else (current or ""))
        if bad:
            problems.append(rel)
            print(f"FAIL  {rel} links {len(bad)} path(s) git does not track: {', '.join(bad[:5])}")
        if current == text:
            print(f"ok    {rel} is current")
        elif args.check:
            problems.append(rel)
            was, now = set((current or "").splitlines()), set(text.splitlines())
            print(f"FAIL  {rel} is stale: {len(now - was)} line(s) to add, {len(was - now)} to drop")
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {rel}")
        if args.check and rel not in tracked():
            problems.append(rel)
            print(f"FAIL  {rel} is not tracked: `git add -- {rel}` and commit it")
    if problems:
        print("\nrun bench/build_index.py, `git add` any new index, and commit the result")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
